# Generated by Django 3.0.3 on 2020-02-06 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_player_unlocked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='unlocked',
            new_name='unlocked_basement',
        ),
        migrations.AddField(
            model_name='player',
            name='unlocked_door',
            field=models.BooleanField(default=False),
        ),
    ]
