# Generated by Django 3.0.3 on 2020-02-07 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0003_auto_20200206_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='unlocked_basement',
        ),
        migrations.RemoveField(
            model_name='player',
            name='unlocked_door',
        ),
    ]
