# Generated by Django 3.0.3 on 2020-02-07 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0004_auto_20200206_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='unlocked_basement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='unlocked_door',
            field=models.BooleanField(default=False),
        ),
    ]
